CREATE TABLE TRANSPORT(
	ID INT NOT NULL,
	NAME VARCHAR2(100),
	DRIVER_NAME VARCHAR2(100),
	MOBILE VARCHAR2(20),
	EMAIL VARCHAR2(50),
	CAPACITY INT,
	AVAILABLE INT,
	OCCUPIED INT,
	DRIVER_ADDRESS VARCHAR2(255),
	PRIMARY KEY (ID)
);

CREATE TABLE STAFF(
	ID INT NOT NULL,
	NAME VARCHAR2(100),
	MOBILE VARCHAR2(20),
	EMAIL VARCHAR2(50),
	ADDRESS VARCHAR2(255),
	TRANSPORT_ID INT,
	PRIMARY KEY (ID),
	FOREIGN KEY (TRANSPORT_ID) REFERENCES TRANSPORT(ID)
);

CREATE TABLE CLASS(
	ID INT NOT NULL,
	NAME VARCHAR2(50),
	LOCATION VARCHAR2(255),
	HEAD_TEACHER_ID INT,
	PRIMARY KEY (ID),
	FOREIGN KEY (HEAD_TEACHER_ID) REFERENCES STAFF(ID)
);

CREATE TABLE SUBJECT(
	ID INT NOT NULL,
	NAME VARCHAR2(50),
	CLASS_ID INT,
	TEACHER_ID INT NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (CLASS_ID) REFERENCES CLASS(ID),
	FOREIGN KEY (TEACHER_ID) REFERENCES STAFF(ID)
);

CREATE TABLE CLASS_SCHEDULE(
	START_TIME DATE,
	END_TIME DATE,
	DURATION INT, -- IN MINUTES
	SUBJECT_ID INT NOT NULL,
	CLASS_ID INT NOT NULL,
	FOREIGN KEY (CLASS_ID) REFERENCES CLASS(ID),
	FOREIGN KEY (SUBJECT_ID) REFERENCES SUBJECT(ID)
);

CREATE TABLE FEE_TEMPLATE(
	ID INT NOT NULL,
	FACILITY VARCHAR2(50),
	FEE_REPEAT VARCHAR2(25), --CAN BE MONTHLY, ANNUAL, ONETIME
	AMOUNT INT, -- IN RUPEES
	DEADLINE INT, -- IN DAYS
	REMINDER INT, -- IN DAYS
	CLASS_ID INT NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (CLASS_ID) REFERENCES CLASS(ID)
);

CREATE TABLE ORGANIZATION(
	ID INT NOT NULL,
	NAME VARCHAR2(100),
	ADDRESS VARCHAR2(255),
	PRIMARY KEY (ID)
);

CREATE TABLE USERS(
	ID INT NOT NULL,
	NAME VARCHAR2(100),
	LOGIN VARCHAR2(50),
	PASSWORD VARCHAR2(50),
	ORGANIZATION_ID INT NOT NULL,
	ROLE VARCHAR2(50),
	PRIMARY KEY (ID),
	FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATION(ID)
);

CREATE TABLE STUDENT(
	ID INT NOT NULL,
	NAME VARCHAR2(100),
	EMAIL VARCHAR2(50),
	ADDRESS VARCHAR2(255),
	MOBILE VARCHAR2(20),
	CLASS_ID INT NOT NULL,
	TRANSPORT_ID INT,
	PRIMARY KEY (ID),
	FOREIGN KEY (CLASS_ID) REFERENCES CLASS(ID),
	FOREIGN KEY (TRANSPORT_ID) REFERENCES TRANSPORT(ID)
);

CREATE TABLE STUDENT_FACILITIES(
	ID INT NOT NULL,
	FACILITY VARCHAR2(100),
	FEE_TEMPLATE_ID INT,
	STUDENT_ID INT,
	PRIMARY KEY (ID),
	FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(ID),
	FOREIGN KEY (FEE_TEMPLATE_ID) REFERENCES FEE_TEMPLATE(ID)
);

CREATE TABLE STAFF_PROC_REQ(
	ID INT NOT NULL,
	REQ_DATE TIMESTAMP,
	LAST_UPDATE_DATE TIMESTAMP,
	REQUEST BLOB,
	STATUS VARCHAR2(25),
	PRIMARY KEY (ID)
);

CREATE TABLE STAFF_PROC_RES(
	ID INT NOT NULL,
	RESPONSE BLOB,
	REQ_ID INT NOT NULL,
	STATUS VARCHAR2(25),
	PRIMARY KEY (ID),
	FOREIGN KEY (REQ_ID) REFERENCES STAFF_PROC_REQ(ID)
);

CREATE TABLE STAFF_PROC_CANDIDATES(
	ID INT NOT NULL,
	NAME VARCHAR2(100),
	MOBILE VARCHAR2(20),
	EMAIL VARCHAR2(50),
	AGE INT,
	RES_ID INT NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (RES_ID) REFERENCES STAFF_PROC_RES(ID)
);



CREATE TABLE TRANSPORT_PROC_REQ(
	ID INT NOT NULL,
	REQ_DATE TIMESTAMP,
	LAST_UPDATE_DATE TIMESTAMP,
	REQUEST BLOB,
	STATUS VARCHAR2(25),
	PRIMARY KEY (ID)
);

CREATE TABLE TRANSPORT_PROC_RES(
	ID INT NOT NULL,
	RESPONSE BLOB,
	REQ_ID INT NOT NULL,
	STATUS VARCHAR2(25),
	PRIMARY KEY (ID),
	FOREIGN KEY (REQ_ID) REFERENCES TRANSPORT_PROC_REQ(ID)
);

CREATE TABLE TRANSPORT_PROC_VEHICLES(
	ID INT NOT NULL,
	NAME VARCHAR2(100),
	MOBILE VARCHAR2(20),
	EMAIL VARCHAR2(50),
	RES_ID INT NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (RES_ID) REFERENCES TRANSPORT_PROC_RES(ID)
);

CREATE TABLE FEE_LIABILITY(
	ID INT NOT NULL,
	AMOUNT INT,
	DEADLINE TIMESTAMP,
	REMINDER TIMESTAMP,
	REMINDER_2 TIMESTAMP,
	PAID INT,
	BALANCE INT,
	STUDENT_ID INT NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(ID)
);

CREATE TABLE FEE_PAYMENTS(
	ID INT NOT NULL,
	PAYMENT INT,
	FEE_LIABILITY_ID INT NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (FEE_LIABILITY_ID) REFERENCES FEE_LIABILITY(ID)
);